"""Writes the OpenFOAM case: fields, physical properties and solver control.

Generated rather than hand-edited because angle of attack changes four things
at once — the inlet velocity vector and the lift and drag directions in the
force coefficients — and editing those by hand for every alpha in a sweep is
how a polar ends up with one point computed against the wrong reference.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path

HEAD = """FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    location    "{loc}";
    object      {obj};
}}
// Generated by src/case.py — do not edit by hand.
"""


@dataclass(frozen=True)
class Case:
    """Flow conditions and solver settings for a 2D aerofoil run.

    alpha_deg   angle of attack
    reynolds    based on chord and freestream speed
    velocity    freestream speed, m/s (chord is 1 m, so nu follows from Re)
    span        cell-layer thickness, m — sets the reference area
    iterations  maximum SIMPLE iterations
    """

    alpha_deg: float = 0.0
    reynolds: float = 6.0e6
    velocity: float = 1.0
    chord: float = 1.0
    span: float = 0.02
    iterations: int = 3000
    residual_tolerance: float = 1.0e-6

    @property
    def nu(self) -> float:
        return self.velocity * self.chord / self.reynolds

    @property
    def flow_direction(self) -> tuple[float, float]:
        a = math.radians(self.alpha_deg)
        return (math.cos(a), math.sin(a))

    @property
    def lift_direction(self) -> tuple[float, float]:
        a = math.radians(self.alpha_deg)
        return (-math.sin(a), math.cos(a))

    # Menter's external-aerodynamics guidance: omega_inf a few times U/L over
    # the domain, and a freestream eddy viscosity small against the molecular
    # one so the far field does not seed turbulence into the boundary layer.
    @property
    def omega_inf(self) -> float:
        return 5.0 * self.velocity / (30.0 * self.chord)

    @property
    def nut_inf(self) -> float:
        return 1.0e-3 * self.nu

    @property
    def k_inf(self) -> float:
        return self.nut_inf * self.omega_inf

    def _field(self, obj, dims, internal, wall, freestream, cls="volScalarField"):
        return f"""{HEAD.format(cls=cls, loc="0", obj=obj)}
dimensions      {dims};

internalField   uniform {internal};

boundaryField
{{
    aerofoil        {{ {wall} }}
    inlet           {{ {freestream} }}
    outlet          {{ {freestream} }}
    topAndBottom    {{ {freestream} }}
    frontAndBack    {{ type empty; }}
}}
"""

    def write(self, case_dir) -> list[Path]:
        case = Path(case_dir)
        (case / "0").mkdir(parents=True, exist_ok=True)
        (case / "constant").mkdir(parents=True, exist_ok=True)
        (case / "system").mkdir(parents=True, exist_ok=True)

        ux, uy = (c * self.velocity for c in self.flow_direction)
        u_vec = f"({ux:.10g} {uy:.10g} 0)"
        written = []

        def put(rel, text):
            p = case / rel
            p.write_text(text)
            written.append(p)

        put("0/U", self._field(
            "U", "[0 1 -1 0 0 0 0]", u_vec,
            "type noSlip;",
            f"type freestreamVelocity; freestreamValue uniform {u_vec};",
            cls="volVectorField"))

        put("0/p", self._field(
            "p", "[0 2 -2 0 0 0 0]", "0",
            "type zeroGradient;",
            "type freestreamPressure; freestreamValue uniform 0;"))

        # Low-Re wall treatment: the mesh is built for y+ ~ 1, so the boundary
        # layer is resolved rather than modelled. omegaWallFunction is still the
        # right wall condition — it blends to the analytical viscous-sublayer
        # value as y+ falls below about 3.
        put("0/k", self._field(
            "k", "[0 2 -2 0 0 0 0]", f"{self.k_inf:.6g}",
            "type fixedValue; value uniform 1e-12;",
            f"type freestream; freestreamValue uniform {self.k_inf:.6g};"))

        put("0/omega", self._field(
            "omega", "[0 0 -1 0 0 0 0]", f"{self.omega_inf:.6g}",
            "type omegaWallFunction; value uniform 1e-8;",
            f"type freestream; freestreamValue uniform {self.omega_inf:.6g};"))

        put("0/nut", self._field(
            "nut", "[0 2 -1 0 0 0 0]", f"{self.nut_inf:.6g}",
            "type nutLowReWallFunction; value uniform 0;",
            f"type freestream; freestreamValue uniform {self.nut_inf:.6g};"))

        put("constant/transportProperties",
            HEAD.format(cls="dictionary", loc="constant", obj="transportProperties")
            + f"\ntransportModel  Newtonian;\nnu              {self.nu:.10g};\n")

        put("constant/turbulenceProperties",
            HEAD.format(cls="dictionary", loc="constant", obj="turbulenceProperties")
            + "\nsimulationType  RAS;\n\nRAS\n{\n    model        kOmegaSST;\n"
              "    turbulence   on;\n    printCoeffs  on;\n}\n")

        put("system/fvSchemes", self._fv_schemes())
        put("system/fvSolution", self._fv_solution())
        put("system/controlDict", self._control_dict())
        return written

    def _fv_schemes(self) -> str:
        return HEAD.format(cls="dictionary", loc="system", obj="fvSchemes") + """
ddtSchemes      { default steadyState; }

// Unlimited. `cellLimited Gauss linear 1` is the usual safe default and it is
// wrong here: on this mesh it reported Cl = 0.049 for a symmetric section at
// zero incidence, where symmetry requires zero, and inflated Cd from 0.0116 to
// 0.0196. The limiter is nonlinear, so it clips gradients asymmetrically in the
// boundary layer and adds spurious diffusion. A structured C-grid with maximum
// non-orthogonality under 70 does not need it. Re-introduce a limiter only if a
// coarser or worse-quality mesh will not converge without one — and re-check
// the zero-incidence lift afterwards if you do.
gradSchemes     { default Gauss linear; }

// Bounded second-order upwind on the divergence terms. Pure linear is
// unbounded and diverges on a steady run; first-order upwind converges
// obediently and smears the boundary layer enough to spoil the drag.
divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,k)      bounded Gauss limitedLinear 1;
    div(phi,omega)  bounded Gauss limitedLinear 1;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}

laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes   { default corrected; }
wallDist        { method meshWave; }
"""

    def _fv_solution(self) -> str:
        return HEAD.format(cls="dictionary", loc="system", obj="fvSolution") + f"""
solvers
{{
    p
    {{
        solver          GAMG;
        tolerance       1e-8;
        relTol          0.01;
        smoother        GaussSeidel;
    }}
    "(U|k|omega)"
    {{
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-9;
        relTol          0.01;
    }}
}}

SIMPLE
{{
    nNonOrthogonalCorrectors 1;
    consistent      yes;
    residualControl
    {{
        p               {self.residual_tolerance:g};
        U               {self.residual_tolerance:g};
        "(k|omega)"     {self.residual_tolerance:g};
    }}
}}

relaxationFactors
{{
    equations
    {{
        U               0.9;
        "(k|omega)"     0.7;
    }}
}}
"""

    def _control_dict(self) -> str:
        lx, ly = self.lift_direction
        dx, dy = self.flow_direction
        return HEAD.format(cls="dictionary", loc="system", obj="controlDict") + f"""
application     simpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {self.iterations};
deltaT          1;
writeControl    timeStep;
writeInterval   {self.iterations};
purgeWrite      1;
writeFormat     ascii;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;

functions
{{
    // Logged every iteration so convergence can be judged on the coefficients
    // themselves. Residuals falling is not the same as the forces settling,
    // and it is the forces that are being reported.
    forceCoeffs
    {{
        type            forceCoeffs;
        libs            (forces);
        writeControl    timeStep;
        writeInterval   1;
        patches         (aerofoil);
        rho             rhoInf;
        rhoInf          1;
        liftDir         ({lx:.10g} {ly:.10g} 0);
        dragDir         ({dx:.10g} {dy:.10g} 0);
        CofR            (0.25 0 0);
        pitchAxis       (0 0 1);
        magUInf         {self.velocity:.10g};
        lRef            {self.chord:.10g};
        Aref            {self.chord * self.span:.10g};
    }}

    yPlus
    {{
        type            yPlus;
        libs            (fieldFunctionObjects);
        writeControl    writeTime;
    }}
}}
"""
