"""Structured C-grid blockMeshDict generator for a 2D aerofoil.

Four blocks in the classic C arrangement:

    front upper : aerofoil upper surface  <->  far-field arc, upper quarter
    front lower : aerofoil lower surface  <->  far-field arc, lower quarter
    wake upper  : wake centreline         <->  far-field top
    wake lower  : wake centreline         <->  far-field bottom

The far-field arc is centred on the **trailing edge**, not the leading edge or
mid-chord. That choice makes both radial edges of the front blocks genuinely
radial — the trailing edge runs straight out to (x_te, ±R) and the leading edge
straight upstream to (x_te - R, 0) — which keeps the cells near the aerofoil
close to orthogonal. Centring the arc anywhere else skews exactly the cells
whose quality matters most.

Written as a generator rather than a hand-edited dictionary because the mesh
has to be rebuilt at several refinements for a mesh-independence study, and
editing 200 lines of vertex coordinates by hand four times is how a study ends
up comparing meshes that differ in more than their refinement.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from pathlib import Path

from .airfoil import NACA4

HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by src/cgrid.py — do not edit by hand.                            |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


@dataclass(frozen=True)
class CGrid:
    """A C-grid around a NACA section.

    chord            aerofoil chord, m
    far_radius       far-field arc radius, in chords
    wake_length      distance from trailing edge to outlet, in chords
    n_surface        cells along the aerofoil, per surface
    n_normal         cells from the aerofoil out to the far field
    n_wake           cells from the trailing edge to the outlet
    expansion_normal grading from wall to far field (>1 coarsens outward)
    expansion_wake   grading along the wake
    thickness        span of the single cell layer, m. Arbitrary in 2D — the
                     spanwise direction has one cell and an empty boundary, so
                     no gradient exists across it. Sized comparable to the
                     in-plane cells so it does not dominate the aspect ratio
                     with a number that means nothing physically.
    """

    section: NACA4 = field(default_factory=lambda: NACA4.from_code("0012"))
    chord: float = 1.0
    far_radius: float = 12.0
    wake_length: float = 20.0
    n_surface: int = 80
    n_normal: int = 60
    n_wake: int = 60
    expansion_normal: float = 400.0
    expansion_wake: float = 12.0
    thickness: float = 0.02

    def __post_init__(self) -> None:
        if self.far_radius <= 2:
            raise ValueError(
                f"far_radius {self.far_radius} chords is too close. Blockage "
                f"and far-field interference dominate the answer below about "
                f"10 chords; the usual choice is 12 to 20."
            )
        if self.wake_length <= self.far_radius:
            raise ValueError(
                "wake_length must exceed far_radius, or the outlet cuts inside "
                "the far-field arc and the domain is not closed"
            )
        for name, n in (("n_surface", self.n_surface),
                        ("n_normal", self.n_normal), ("n_wake", self.n_wake)):
            if n < 8:
                raise ValueError(f"{name}={n} is too coarse to resolve anything")

    # ── Geometry ────────────────────────────────────────────────────────────

    @property
    def te(self) -> tuple[float, float]:
        return (self.chord, 0.0)

    @property
    def radius(self) -> float:
        return self.far_radius * self.chord

    def surface_points(self, upper: bool) -> list[tuple[float, float]]:
        """Aerofoil surface, leading edge to trailing edge, scaled to chord."""
        up, low = self.section.surfaces(self.n_surface + 1)
        pts = up if upper else low
        return [(x * self.chord, z * self.chord) for x, z in pts]

    def arc_point(self, degrees: float) -> tuple[float, float]:
        """A point on the far-field arc, measured from the trailing edge."""
        rad = math.radians(degrees)
        return (self.te[0] + self.radius * math.cos(rad),
                self.te[1] + self.radius * math.sin(rad))

    # ── Near-wall spacing ───────────────────────────────────────────────────

    def first_cell_height(self) -> float:
        """Height of the cell against the aerofoil, from the radial grading.

        simpleGrading gives the ratio of last cell to first across the block, so
        the first cell follows from summing the geometric series to the block's
        radial length.
        """
        n = self.n_normal
        ratio = self.expansion_normal ** (1.0 / (n - 1))
        total = (ratio ** n - 1.0) / (ratio - 1.0)
        return self.radius / total

    def y_plus_estimate(self, reynolds: float, velocity: float = 1.0) -> float:
        """Estimated y+ on the first cell centre.

        Flat-plate correlation Cf = 0.0576 Re^-0.2 — approximate, and the point
        is the order of magnitude. The real y+ has to be read back off the
        solution, which is what the validation step does.
        """
        nu = velocity * self.chord / reynolds
        cf = 0.0576 * reynolds ** -0.2
        u_tau = velocity * math.sqrt(cf / 2.0)
        return 0.5 * self.first_cell_height() * u_tau / nu

    def expansion_for_y_plus(self, target: float, reynolds: float,
                             velocity: float = 1.0) -> float:
        """Radial expansion ratio that puts the first cell near `target` y+."""
        nu = velocity * self.chord / reynolds
        cf = 0.0576 * reynolds ** -0.2
        u_tau = velocity * math.sqrt(cf / 2.0)
        wanted = 2.0 * target * nu / u_tau
        lo, hi = 1.0001, 1e9
        for _ in range(200):
            mid = math.sqrt(lo * hi)
            trial = CGrid(**{**self.__dict__, "expansion_normal": mid})
            if trial.first_cell_height() > wanted:
                lo = mid
            else:
                hi = mid
        return math.sqrt(lo * hi)

    # ── Dictionary ──────────────────────────────────────────────────────────
    #
    # Six blocks, not four. Each surface is split at mid-chord because
    # blockMesh identifies an edge by its vertex pair: with the whole upper
    # surface running leading edge to trailing edge and the whole lower surface
    # doing the same, both would be the edge (LE, TE) and only one definition
    # can exist. Splitting gives every curved edge a unique pair.
    #
    # The trailing edge stays a single shared vertex so the two wake blocks
    # meet along the wake centreline. The leading edge and the upstream point
    # are shared too, so the front blocks join along the upstream axis.

    def _plane_points(self) -> list[tuple[float, float]]:
        c, R, L = self.chord, self.radius, self.wake_length * self.chord
        xte = self.te[0]
        upper, lower = self.surface_points(True), self.surface_points(False)
        mid_u = upper[self._mid_index(upper)]
        mid_l = lower[self._mid_index(lower)]
        return [
            (xte, 0.0),                 # 0  trailing edge
            mid_u,                      # 1  upper surface at mid-chord
            (0.0, 0.0),                 # 2  leading edge
            mid_l,                      # 3  lower surface at mid-chord
            (xte, R),                   # 4  far field above TE
            self.arc_point(135.0),      # 5  far field, upper quarter
            (xte - R, 0.0),             # 6  far field, upstream
            self.arc_point(225.0),      # 7  far field, lower quarter
            (xte, -R),                  # 8  far field below TE
            (xte + L, R),               # 9  outlet top
            (xte + L, 0.0),             # 10 outlet, on the wake line
            (xte + L, -R),              # 11 outlet bottom
        ]

    def _mid_index(self, points) -> int:
        """Index of the surface point nearest mid-chord.

        Segments are split by index, never by comparing x against 0.5*chord.
        Cosine spacing puts that point at 0.49999999999999994, so `x <= 0.5`
        and `x < 0.5` both accept it — the block corner then appears again as
        an interior point of the polyLine, and it does so on one surface but
        not its mirror. The result was a mesh asymmetric about y=0, which a
        symmetric section at zero incidence reported as a lift coefficient of
        0.049 where symmetry requires exactly zero.
        """
        target = 0.5 * self.chord
        return min(range(len(points)), key=lambda i: abs(points[i][0] - target))

    @staticmethod
    def _is_anticlockwise(quad) -> bool:
        """Shoelace sign. blockMesh rejects a clockwise base face as inside-out."""
        total = 0.0
        for (x1, y1), (x2, y2) in zip(quad, quad[1:] + quad[:1]):
            total += x1 * y2 - x2 * y1
        return total > 0

    def _blocks(self) -> list[tuple[str, tuple[int, int, int, int],
                              tuple[int, int, int], tuple[float, float, float]]]:
        ns, nn, nw = self.n_surface // 2, self.n_normal, self.n_wake
        en, ew = self.expansion_normal, self.expansion_wake
        # (name, base-plane vertices, cell counts, grading)
        return [
            ("upper aft", (0, 4, 5, 1), (nn, ns, 1), (en, 1, 1)),
            ("upper fwd", (1, 5, 6, 2), (nn, ns, 1), (en, 1, 1)),
            ("lower fwd", (2, 6, 7, 3), (nn, ns, 1), (en, 1, 1)),
            ("lower aft", (3, 7, 8, 0), (nn, ns, 1), (en, 1, 1)),
            ("wake upper", (0, 10, 9, 4), (nw, nn, 1), (ew, en, 1)),
            ("wake lower", (0, 8, 11, 10), (nn, nw, 1), (en, ew, 1)),
        ]

    def to_dict(self) -> str:
        plane = self._plane_points()
        n = len(plane)

        for name, quad, _, _ in self._blocks():
            if not self._is_anticlockwise([plane[i] for i in quad]):
                raise ValueError(
                    f"block {name!r} {quad} is clockwise in the base plane; "
                    f"blockMesh would reject it as inside-out"
                )

        lines = [HEADER, "scale   1;", "", "vertices", "("]
        for z in (0.0, self.thickness):
            for x, y in plane:
                lines.append(f"    ({x:.8g} {y:.8g} {z:.8g})")
        lines += [");", "", "blocks", "("]
        for name, (a, b, c_, d), (i, j, k), (gi, gj, gk) in self._blocks():
            quad = f"({a} {b} {c_} {d} {a+n} {b+n} {c_+n} {d+n})"
            lines.append(f"    hex {quad} ({i} {j} {k}) "
                         f"simpleGrading ({gi} {gj} {gk})  // {name}")
        lines += [");", "", "edges", "("]

        upper, lower = self.surface_points(True), self.surface_points(False)
        iu, il = self._mid_index(upper), self._mid_index(lower)
        # Interior points only: endpoints are block corners and must not be
        # repeated inside the polyLine that connects them.
        seg = {
            (0, 1): list(reversed(upper[iu + 1:-1])),
            (1, 2): list(reversed(upper[1:iu])),
            (2, 3): lower[1:il],
            (3, 0): lower[il + 1:-1],
        }
        arcs = {(4, 5): 112.5, (5, 6): 157.5, (6, 7): 202.5, (7, 8): 247.5}

        for z, off in ((0.0, 0), (self.thickness, n)):
            for (a, b), pts in seg.items():
                if not pts:
                    continue
                lines.append(f"    polyLine {a+off} {b+off}")
                lines.append("    (")
                lines.append("\n".join(
                    f"        ({x:.8g} {y:.8g} {z:.8g})" for x, y in pts))
                lines.append("    )")
            for (a, b), deg in arcs.items():
                mx, my = self.arc_point(deg)
                lines.append(f"    arc {a+off} {b+off} ({mx:.8g} {my:.8g} {z:.8g})")

        lines += [");", ""]
        lines += self._boundary(n)
        return "\n".join(lines) + "\n"

    def _boundary(self, n: int) -> list[str]:
        def face(a, b):
            return f"            ({a} {b} {b+n} {a+n})"

        def block_face(quad):
            a, b, c_, d = quad
            return (f"            ({a} {b} {c_} {d})",
                    f"            ({d+n} {c_+n} {b+n} {a+n})")

        front, back = [], []
        for _, quad, _, _ in self._blocks():
            f, b = block_face(quad)
            front.append(f)
            back.append(b)

        return [
            "boundary", "(",
            "    aerofoil", "    {", "        type wall;", "        faces", "        (",
            face(0, 1), face(1, 2), face(2, 3), face(3, 0),
            "        );", "    }", "",
            "    inlet", "    {", "        type patch;", "        faces", "        (",
            face(4, 5), face(5, 6), face(6, 7), face(7, 8),
            "        );", "    }", "",
            "    outlet", "    {", "        type patch;", "        faces", "        (",
            face(9, 10), face(10, 11),
            "        );", "    }", "",
            "    topAndBottom", "    {", "        type patch;", "        faces", "        (",
            face(4, 9), face(11, 8),
            "        );", "    }", "",
            "    frontAndBack", "    {", "        type empty;", "        faces", "        (",
            *front, *back,
            "        );", "    }",
            ");", "",
        ]

    def write(self, path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.to_dict())
        return path
